sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t javiergt85/docker-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true javiergt85/docker-udemy npm run test